library(forecast)
#Dow-Jones index on 292 trading days ending 26 Aug 1994
data("dj", package = "fma")
par(mfrow=c(1,1))
plot(dj)
retdj<-diff(log(dj))
plot(retdj)
acf(dj, lag.max = 30, na=na.omit, main="", ylab="ACF", xlab="Lag")
#acf(retdj, lag.max = 30, na=na.omit, main="", ylab="ACF", xlab="Lag",ylim=c(-0.2,0.2))
acf(retdj, lag.max = 30, na=na.omit, main="", ylab="ACF", xlab="Lag")
ar2<-arima.sim(model=list(ar=c(.9,-.2)),n=100) + 0.3
ar1<-arima.sim(model=list(ar=c(.8)),n=100) 
plot(ar2)
plot(ar1)
acf(ar1)
pacf(ar1)
acf(ar2)
pacf(ar2)
ma2<-arima.sim(model=list(ma=c(-.7,.1)),n=100)
ma1<-arima.sim(model=list(ma=c(.4)),n=100) + 0.1
plot(ma1)
plot(ma2)
acf(ma1, lag.max = 40)
pacf(ma1,lag.max = 40)
acf(ma2)
pacf(ma2)
set.seed(123)
wn = rnorm(500, mean=0, sd=1)
plot(wn, type="l", ylab="wn", xlab="time")
acf(wn)
rw <- cumsum(rnorm(500, mean = 0))
plot(rw, type="l", ylab="rw", xlab="time")
acf(rw)
